name: Web Linting & Type Checking

on:
    push:
        branches: [main, develop]
        paths:
            - "apps/web/**"
            - "packages/**"
            - ".github/workflows/web-lint.yml"
    pull_request:
        branches: [main, develop]
        paths:
            - "apps/web/**"
            - "packages/**"
            - ".github/workflows/web-lint.yml"

jobs:
    lint:
        name: ESLint Check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint --workspace=apps/web

            - name: Check if issues are fixable
              if: failure()
              run: |
                  echo "❌ ESLint issues found!"
                  echo "Run the following command locally to fix auto-fixable issues:"
                  echo "  npm run lint --workspace=apps/web"
                  exit 1

    type-check:
        name: TypeScript Type Check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run TypeScript type check
              run: npm run type-check --workspace=apps/web

            - name: Type check failed
              if: failure()
              run: |
                  echo "❌ TypeScript type checking failed!"
                  echo "Run the following command locally to see errors:"
                  echo "  npm run type-check --workspace=apps/web"
                  exit 1

    build:
        name: Next.js Build Check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build Next.js app
              run: npm run build --workspace=apps/web
              env:
                  NEXT_PUBLIC_API_URL: http://localhost:8000
                  NEXT_PUBLIC_GRAPHQL_URL: http://localhost:8000/graphql

            - name: Build failed
              if: failure()
              run: |
                  echo "❌ Next.js build failed!"
                  echo "Run the following command locally to debug:"
                  echo "  npm run build --workspace=apps/web"
                  exit 1

    format-check:
        name: Prettier Format Check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Check Prettier formatting
              run: npx prettier --check "apps/web/**/*.{ts,tsx,js,jsx,json,css,md}" --ignore-path .prettierignore

            - name: Format check failed
              if: failure()
              run: |
                  echo "❌ Prettier formatting issues found!"
                  echo "Run the following command locally to fix:"
                  echo "  npm run format"
                  exit 1

    storybook-tests:
        name: Storybook Interaction Tests
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps
              working-directory: ./apps/web

            - name: Run Storybook tests
              run: npm run test-storybook:ci --workspace=apps/web

            - name: Storybook tests failed
              if: failure()
              run: |
                  echo "❌ Storybook interaction tests failed!"
                  echo "Run the following command locally to debug:"
                  echo "  npm run storybook"
                  echo "  npm run test-storybook"
                  exit 1

    e2e-tests:
        name: Playwright E2E Tests
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps
              working-directory: ./apps/web

            - name: Run Playwright e2e tests
              run: npm run test:e2e --workspace=apps/web
              env:
                  NEXT_PUBLIC_API_URL: http://localhost:8000
                  NEXT_PUBLIC_GRAPHQL_URL: http://localhost:8000/graphql

            - name: Upload Playwright report
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: apps/web/playwright-report/
                  retention-days: 7

            - name: E2E tests failed
              if: failure()
              run: |
                  echo "❌ Playwright e2e tests failed!"
                  echo "Run the following command locally to debug:"
                  echo "  npm run test:e2e --workspace=apps/web"
                  exit 1

    summary:
        name: Web Lint Summary
        runs-on: ubuntu-latest
        needs: [lint, type-check, build, format-check, storybook-tests, e2e-tests]
        if: always()

        steps:
            - name: Check overall status
              run: |
                  if [ "${{ needs.lint.result }}" == "failure" ] || \
                     [ "${{ needs.type-check.result }}" == "failure" ] || \
                     [ "${{ needs.build.result }}" == "failure" ] || \
                     [ "${{ needs.format-check.result }}" == "failure" ] || \
                     [ "${{ needs.storybook-tests.result }}" == "failure" ] || \
                     [ "${{ needs.e2e-tests.result }}" == "failure" ]; then
                    echo "::error::One or more checks failed. Please review the logs above."
                    exit 1
                  else
                    echo "✅ All web checks passed!"
                  fi
